config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'places#index'
  resources :places do
    resources :comments, only: :create
    resources :photos, only: :create
  end
  resources :users, only: :show
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :place
  belongs_to :user
  after_create :send_comment_email

    def send_comment_email
      NotificationMailer.comment_added(self).deliver
    end
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :place
  mount_uploader :picture, PictureUploader
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :photos
  
  geocoded_by :address
  after_validation :geocode
  
  validates :name, length: { minimum: 3 }
  validates :address, presence: true
  validates :description, presence: true

  def average_rating
    if comments.count == 0
      return "no ratings"
    end
    rating_integers = []
    comments.each do |c|
      rating_integers << c.rating.to_i
    end
    (rating_integers.sum.to_f / rating_integers.length).round(2)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :places
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @place = Place.find(params[:place_id])
    @place.comments.create(comment_params.merge(user: current_user))
    redirect_to place_path(@place)
  end
  
  private
  
  def comment_params
    params.require(:comment).permit(:message, :rating)
  end
    
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!

  def create
    @place = Place.find(params[:place_id])
    @place.photos.create(photo_params)
    redirect_to place_path(@place)
  end

  private

  def photo_params
    params.require(:photo).permit(:caption,:picture, :place_id)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @places = Place.all.paginate(:page => params[:page], :per_page => 4)

  end

  def new
    @place = Place.new
  end

  def create
    @place = current_user.places.create(place_params)
    if @place.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @place = Place.find_by_id(params[:id])
    @comment = Comment.new
    @photo = Photo.new
  end

  def edit
    @place = Place.find_by_id(params[:id])

    if @place.user != current_user
      return render text: 'Not Allowed', status: :forbidden
    end
  end

  def update
    @place = Place.find_by_id(params[:id])
    if @place.user != current_user
      return render text: 'Not Allowed', status: :forbidden
    end
    
    @place.update_attributes(place_params)
    if @place.valid?
      redirect_to place_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @place = Place.find_by_id(params[:id])
    if @place.user != current_user
      return render text: 'Not Allowed', status: :forbidden
    end
    @place.destroy
    redirect_to root_path
  end

  private

  def place_params
    params.require(:place).permit(:name, :address, :description)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NomsterNew</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-primary pimped-nav">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= link_to 'MusicRoomFinder', root_path, class: 'navbar-brand' %>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item">
            <%= link_to new_place_path, class: 'nav-link' do %>
              <i class="fa fa-plus-circle"></i>
              New Place
            <% end %>
        </ul>
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
            <li class = "nav-item">
              <%= link_to 'My profile', user_path(current_user), class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <br />
    <% if notice.present? %>
      <p class="alert alert-info col-10 offset-1"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger col-10 offset-1"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/places/edit.html.erb
<div class = "booyah-box col-10 offset-1">
  
  <h1>Edit</h1>
  <br />
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.submit 'Edit', class: 'btn btn-primary col-12' %>
  <% end %>
  <br />

</div>

app/views/places/index.html.erb
<div class = "row col-10 offset-1">

<!-- Carousel slider -->
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <%= image_tag 'slider-1.jpg', class: "img-fluid" %>
        <div class="carousel-caption d-none d-md-block">
          <h3>Find music practice rooms</h3>
        </div>
    </div>
    <div class="carousel-item">
      <%= image_tag 'slider-2.jpg', class: "img-fluid" %>
        <div class="carousel-caption d-none d-md-block">
          <h3>Caption 2</h3>
        </div>
    </div>
    <div class="carousel-item">
      <%= image_tag 'slider-3.jpg', class: "img-fluid" %>
        <div class="carousel-caption d-none d-md-block">
          <h3>Caption 3</h3>
        </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<!-- Places cards -->
  <% @places.each do |place| %>
  <div class = "col-md-6">
  <div class = "card card-1">
    <% if place.photos.present? %>
      <%= image_tag place.photos.last.picture, height: "260", class: "card-img-top" %>
    <% else %>
      <img class = "card-img-top" src = "https://dummyimage.com/300x260/edfbfc/5b6063&text=Please+add+a+photo" alt = "..." height: "260">
    <% end %>
    <div class = "card-block">
    <h4 class = "card-title"><%= link_to place.name, place_path(place) %></h4>
    <h6 class = "card-subtitle text-muted"><%= place.address %></h6>
    <br />
    <p class = "card-text"><%= place.description %></p>
    </div>
    <div class = "card-footer">
      <small class = "text-muted">    
        <% if place.comments.present? %>
          <div class="col-12">
              <% if place.comments.last.rating.present? %>
                <b><%= place.comments.last.rating %> stars</b> -
              <% end %>
              <%= place.comments.last.message %>
              <small><%= place.comments.last.user.email.chomp %></small>
          </div>
        <% elsif place.user.present? %>
          Submitted by: <%= place.user.email %>
        <% else %>
          Unknown user
        <% end %>
      </small>
    </div>
  </div>
  <br />
  </div>
  <br />
  <% end %>
</div>

<!-- pagination -->
<%= will_paginate @places, class: 'apple_pagination' %>

app/views/places/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Enter Your Place Details</h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.submit 'Create', class: 'btn btn-primary col-12' %>
  <% end %>
  <br />
</div>

app/views/places/show.html.erb
<div class = "booyah-box col-10 offset-1">
  <div class = "row">
    <h1 class = "h1-inline col-12 col-lg-6 float-left"><%= @place.name %></h1>

    <!-- This is something that needs moving to the model, but don't know how to do that yet -->

    <div class = "float-right gold-text col-6 col-lg-3 margin-top-10">
    <h3><b><%= @place.average_rating %></b> stars <small>(<%= @place.comments.count %>)</small></h3></div>


      
      <!-- Buttons for edit and delete visible only to user who created them -->
    <% if current_user == @place.user %>
      <div class = "float-right margin-top-10 col-12 col-lg-3 text-align-right">
          <%= link_to edit_place_path, class: 'btn btn-secondary' do %>
            <i class="fa fa-pencil" aria-hidden="true"></i> Edit
          <% end %>
          <%= link_to place_path(@place), class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?'} do %>
            <i class="fa fa-trash" aria-hidden="true"></i> Delete
          <% end %>
      </div>
    <% end %>
      <div class = "clear"></div>
  </div>



    <br />
    <div class = "clear"></div>
      <i><%= @place.address %></i>
      <br/>

    <!-- Google maps -->
    <% if @place.latitude.present? && @place.longitude.present? %>

    <script>

      function initMap() {
        var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};

        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 15,
          center: myLatLng
        });

        var marker = new google.maps.Marker({
          position: myLatLng,
          map: map,
          title: 'Hello World!'
        });
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAsGe2E7vEhPR9YfAZ522p0Qth7-H4enBM&callback=initMap">
    </script>

    <div id="map"></div>

    <% end %>

    <!-- Address and description -->

    <div class = "clear"/></div>
    <p><%= @place.description %></p>
</div>

<br />

<!-- Comment box -->
<div class = "booyah-box col-10 offset-1">
  <h3 class = "margin-top-10 float-left">Comments</h3>
  <button type="button" class="btn btn-primary float-right margin-top-10 col-12 col-sm-6 col-lg-3" data-toggle="modal" data-target="#CommentModal">+ Add a comment
  </button>
  <div class = "clear"></div>

<!-- Comment cards -->
  <br />
  <div class = "row">
  <% @place.comments.each do |comment| %>
  <div class = "col-12 col-sm-6">

    <div class="card text-center">
      <div class="card-header gold-text">
        <b><%= comment.rating %> stars</b>
      </div>
      <div class="card-block">
        <p class="card-text text-muted">"<%= comment.message %>"</p>
      </div>
      <div class="card-footer text-muted">
        <%= comment.user.email %>
      </div>
    </div>
    <br />
  </div>
  <% end %>
  </div>  
  <br />
  </div>
  <br />
</div>



<!-- Comments Modal -->
<div class="modal fade" id="CommentModal" tabindex="-1" role="dialog" aria-labelledby="CommentModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="CommentModalLabel">Add a comment</h4>
      </div>
      <%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>
        <div class="modal-body">
          <%= f.input :message %>
          <%= f.input :rating, collection: 1..5 %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary col-2" data-dismiss="modal">x</button>
          <%= f.submit "Add comment", class: 'btn btn-primary col-10' %>
        </div>
      <% end %>
    </div>
  </div>
</div>
</div>


<!-- Photos box -->
<div class = "booyah-box col-10 offset-1">
  <h3 class = "margin-top-10 float-left">Photos</h3>
<button type="button" class="btn btn-primary margin-top-10 float-right col-12 col-sm-6 col-lg-3" data-toggle="modal" data-target="#exampleModal">
  + Add Photo
</button>

  <div class = "clear"></div>
  <br />
  <div class = "row">
  <% @place.photos.each do |photo| %>
  <div class = "col-12 col-sm-6">
    <div class="card text-center">
    <% if photo.picture.present? %>
    <%= image_tag photo.picture, height: "260", class: "card-img-top" %>
    <% else %>
    <img class = "card-img-top" src = "http://via.placeholder.com/300x260" alt = "..." height = "260">
    <% end %>
      <div class = "card-block">
        <div class = "card-footer">
          <%= photo.caption %>
        </div>
      </div>
    </div>
    <br />
  </div>
  <% end %>
  </div>
</div>
<br />


<!-- Photo upload modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add a photo</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= simple_form_for @photo, url: place_photos_path(@place) do |f| %>
      <div class="modal-body">
        <%= f.input :caption %>
        <%= f.input :picture %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary col-2" data-dismiss="modal">x</button>
        <%= f.submit "Add photo", class: 'btn btn-primary col-10' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="booyah-box col-10 offset-1">
  <div class = "row">
    <div class = "col-12 col-sm-2">
      <%= image_tag 'user.png', class: 'image-fluid' %>
    </div>

    <div class = "col-12 col-sm-10">
      <h1><%= @user.email %></h1>
      <h6 class = "text-muted">Member since <%= @user.created_at.strftime("%B, %Y") %></h6>
      <h4><b><%= @user.comments.count %></b> total comments</h4>
      <h4><b><%= @user.comments.where(rating: '5_stars').count %></b> total 5 star reviews</h4>
    </div>
  </div>
  <div class = "clear"></div>
</div>

<br />

<div class = "booyah-box col-10 offset-1">
  <h1 class = "text-center margin-top-10">My comments</h1>
  <br />
  <div class = "row">
    <% @user.comments.each do |comment| %>
    <div class = "col-12 col-sm-6">
      <div class="card text-center">
        <div class="card-header">
          <!-- This is where comment.place.name should be, but doesn't currently work -->
          <b><%= link_to comment.place.name, place_path(comment.place) %></b>
        </div>
        <div class="card-block">
          <p class="card-text text-muted">"<%= comment.message %>"</p>
        </div>
        <div class="card-footer gold-text">
          <b><%= comment.rating %></b> stars
        </div>
      </div>
      <br />
    </div>
    <% end %>
  </div>
</div>

<br />

<div class = "booyah-box col-10 offset-1">
  <h1 class = "text-center margin-top-10">My places</h1>
  <br />
  <div class = "row">
    <% @user.places.each do |place| %>
    <div class = "col-12 col-sm-6">
      <div class = "card text-center">
        <div class = "card-header">
          <b><%= link_to place.name, place_path(place) %></b>
        </div>
        <div class = "card-block">
          <p class = "card-text text-muted">
          <% if place.comments.count == 1 %>
          <%= place.comments.count %> comment
          <% else %>
          <%= place.comments.count %> comments
          <% end %>
          </p>
        </div>
      </div>
      <br />
    </div>
    <% end %>
  </div>
</div>